version: '3.8'

services:
  react-app:
    container_name: client
    build:
      context: react-app/
      dockerfile: Dockerfile
    image: client
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/react-app   
    networks:
      - mongodb_network

  # node-server: 
  #   container_name: server
  #   build:  
  #     context: node-server/
  #     dockerfile: Dockerfile
  #   image: server
  #   ports:
  #     - "8080:8080"

    networks:
      - mongodb_network
      
volumes:
  mongodb:
    driver: local
    
networks:
  mongodb_network:
    external: true
