version: '3.8'

services:
  react-app:
    container_name: client
    image: react
    build:
      context: react-app/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes: 
      - react-app:/react-app   
    networks:
      - mongodb_network

  node-server: 
    container_name: server
    image: node
    build:  
      context: node-server/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mongodb_network

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: always 
  #   ports:
  #     - "27017:27017"
  #   environment:   
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password   
  #   volumes:
  #     - mongodb:/data/db
  #   networks: 
  #     - mongodb_network

volumes:
  react-app:
    name: react-app
    driver: local
    
networks:
  mongodb_network:
    name: mongodb_network
# AKIA6GBMDF3T2UYLU3UO
# Oa4Sz8NjT5P5H8MmLkTubGYQKCF6R06l1ujnlssI
