version: '3.8'

services:
  react-app:
    container_name: client
    build:
      context: react-app/
      dockerfile: Dockerfile
    image: 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:v1.0
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/react-app   
    networks:
      - mongodb_network

  node-server: 
    container_name: server
    build:  
      context: node-server/
      dockerfile: Dockerfile
    image: 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:v2.0
    ports:
      - "8080:8080"

    networks:
      - mongodb_network
      
volumes:
  mongodb:
    driver: local
    
networks:
  mongodb_network:
    external: true
