name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the images
        run: |
          docker compose build 

      - name: Down the image
        run: | 
          docker compose down
          
      - name: Run the docker 
        run: | 
          docker compose up -d

      # - name: List Running Containers
      #   run: docker ps
        
      - name: Tear down services
        if: always()
        run: docker compose down
