name: CI/CD Pipeline

on:
 workflow_dispatch: 
  inputs:
   username:
     description: 'Insert Username:'
     required: true
   password:
     description: 'Insert Password:'
     required: true
   
 
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      

      - name: Create .env file
        run: |
          echo "MONGO_INITDB_ROOT_USERNAME=${{ github.event.inputs.username }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ github.event.inputs.password }}" >> .env
         
      - name: Build the images
        run: |
          docker compose build 
         
      - name: Down the images
        run: | 
          docker compose down
       
      - name: Run the docker 
        run: | 
          docker compose up -d
