name: CI/CD Pipeline

on:
 workflow_dispatch
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
         
      - name: Build the images
        run: |
          docker compose build 
         
      - name: Down the image
        run: | 
          docker compose down
       
      - name: Create .env file
        run: |
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
      
      - name: Accessing Secret
        run: | 
            echo "My Username is ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}"
            echo "My Password is ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}"
     
      - name: Run the docker 
        run: | 
          docker compose up -d

      # - name: List Running Containers
      #   run: docker ps
        
      # - name: Tear down services
      #   if: always()
      #   run: docker compose down
