name: CI/CD ecs Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        docker build -t 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client . 
        docker build -t 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server .  

    - name: Log in to Amazon ECR
      run: |
         docker login --username AWS --password-stdin 975050059495.dkr.ecr.us-east-1.amazonaws.com

    - name: Tag and push Docker images to ECR
      run: |
     
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server

    - name: Update ECS Client Service
      uses: aws-actions/amazon-ecs-update-service@v1
      with:
        cluster: Cluster
        service: Front
        image: 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client
        wait-for-service-stability: true

    - name: Update ECS Server Service
      uses: aws-actions/amazon-ecs-update-service@v1
      with:
        cluster: Cluster
        service: Node
        image: 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server
        wait-for-service-stability: true
