name: CI/CD ecs Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Read and increment version tag
      id: version
      run: |
        # Read the current version from version.txt
        CURRENT_VERSION=$(cat version.txt)
        echo "Current version is $CURRENT_VERSION"

        # Increment the version number
        VERSION_PREFIX="v"
        MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f1 | sed 's/^v//')
        MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f2)
        NEW_MINOR=$((MINOR + 1))
        NEW_VERSION="${VERSION_PREFIX}${MAJOR}.${NEW_MINOR}"

        # Update version.txt
        echo $NEW_VERSION > version.txt
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build Docker images
      run: |
        docker compose build
       
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    - name: Log in to Amazon ECR
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050059495.dkr.ecr.us-east-1.amazonaws.com

        
    - name: Tag and push Docker images to ECR
      run: |
        docker tag client:latest 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client-${{ env.VERSION }}
        docker tag server:latest 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server-${{ env.VERSION }}
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client-${{ env.VERSION }}
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server-${{ env.VERSION }}


    - name: Update ECS Client Service
      run: |
        aws ecs update-service \
          --cluster Cluster \
          --service Front \
          --force-new-deployment \
          --region us-east-1

          
    - name: Update ECS Server Service
      run: |
        aws ecs update-service \
          --cluster Cluster \
          --service Node \
          --force-new-deployment \
          --region us-east-1
          
    - name: Commit new version
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "Mihirv2M"
        git config --global user.email "mihirvbrainerhub@gmail.com"
        git add version.txt
        git commit -m "Increment version to ${{ env.VERSION }}"
        git push
