name: CI/CD ECS Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up GitVersion
      uses: GitTools/actions/gitversion-action@v0.11.0
      id: gitversion
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050059495.dkr.ecr.us-east-1.amazonaws.com

    - name: Get the latest image version from ECR
      id: get-version
      run: |
          # Fetch the list of image tags
          TAGS=$(aws ecr list-images --repository-name my-repo --query 'imageIds[*].imageTag' --output text)
          
          # Determine the latest version
          LATEST_VERSION=$(echo "$TAGS" | grep -Eo '[0-9]+\.[0-9]+' | sort -V | tail -n 1)
          
          # If no version is found, start with 1.1
          if [ -z "$LATEST_VERSION" ]; then
            NEW_VERSION="1.1"
          else
            # Increment the minor version
            IFS='.' read -r -a VERSION_PARTS <<< "$LATEST_VERSION"
            MINOR=${VERSION_PARTS[1]}
            NEW_MINOR=$((MINOR + 1))
            NEW_VERSION="${VERSION_PARTS[0]}.${NEW_MINOR}"
          fi

          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    - name: Build Docker images
      run: |
        docker compose build

    - name: Tag and push Docker images to ECR
      run: |
        echo "Tagging and pushing Docker images with version: ${{ env.NEW_VERSION }}"
        docker tag client:latest 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client.${{ env.NEW_VERSION }}
        # docker tag server:latest 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:2.${{ env.IMAGE_VERSION }}
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client-${{ env.NEW_VERSION }}


      # run: |
      
      #   docker tag client:latest 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:1.${{ env.IMAGE_VERSION }}
      #   # docker tag server:latest 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:${{ env.S_VERSION }}
      #   docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:1.${{ env.IMAGE_VERSION }}
      #   # docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:${{ env.S_VERSION }}

    # - name: Update ECS Client Service
    #   run: |
    #     aws ecs update-service \
    #       --cluster Cluster \
    #       --service Front \
    #       --force-new-deployment \
    #       --region us-east-1

    # - name: Update ECS Server Service
    #   run: |
    #     aws ecs update-service \
    #       --cluster Cluster \
    #       --service Node \
    #       --force-new-deployment \
    #       --region us-east-1
