name: CI/CD ecs Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        docker compose build
       
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    - name: Log in to Amazon ECR
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050059495.dkr.ecr.us-east-1.amazonaws.com

        
    - name: Tag and push Docker images to ECR
      run: |
     
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:1.0
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:2.0
        
    - name: Register new ECS Task Definition Revision
      id: register-task-def
      run: |
        TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://client-definition.json \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
        echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> $GITHUB_ENV

    - name: Create ECS Cluster
      run: |
        aws ecs create-cluster --cluster-name Demo --region ${{ secrets.AWS_REGION }}

    - name: Update ECS Client Service with New Task Definition Revision
      uses: aws-actions/amazon-ecs-update-service@v1
      with:
        cluster: Cluster
        service: Front
        task-definition: ${{ env.TASK_DEFINITION_ARN }}
        force-new-deployment: true
        wait-for-service-stability: true


    # - name: Update ECS Client Service
    #   run: |
    #     aws ecs update-service \
    #       --cluster Cluster \
    #       --container-definitions file://client-container-definition.json \
    #       --service Front \
    #       --force-new-deployment \
    #       --region us-east-1

          
    - name: Update ECS Server Service
      run: |
        aws ecs update-service \
          --cluster Cluster \
          --service Node \
          --force-new-deployment \
          --region us-east-1
