
name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/v}")
          docker build -t mihirv21:client 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client-$TAG ./client
          docker build -t mihirv21:server 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server-$TAG ./server
          docker push mihirv21:client 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client-$TAG
          docker push mihirv21:server 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server-$TAG

  update-version-tag:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine new version
        id: get_version
        run: |
          latest_tag=$(git tag -l "v*" | sort -V | tail -n1)
          new_version=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
          echo "New version: v$new_version"
          echo "VERSION=v$new_version" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag -a $VERSION -m "Release version $VERSION"
          git push origin $VERSION

      - name: Clean up old tags
        run: |
          git tag -d $(git tag -l | grep -v $VERSION)
          git push origin --delete $(git tag -l | grep -v $VERSION)

      - name: Update ECS Client Service
        run: |
          aws ecs update-service \
            --cluster Cluster \
            --service Front \
            --force-new-deployment \
            --region us-east-1
             
      - name: Update ECS Server Service
        run: |
          aws ecs update-service \
            --cluster Cluster \
            -- service Node \
            --force-new-deployment \
            --region us-east-1
