name: CI/CD ecs Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        cd react-app
        docker build -t 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client . 
        cd ..
        cd node-server
        docker build -t 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server .  
        cd ..

    - name: Log in to Amazon ECR
      run: |
         docker login --username AWS --password-stdin 975050059495.dkr.ecr.us-east-1.amazonaws.com

    - name: Tag and push Docker images to ECR
      run: |
     
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:client
        docker push 975050059495.dkr.ecr.us-east-1.amazonaws.com/mihirv21:server

    - name: Update ECS Client Service
      run: |
        aws ecs update-service \
          --cluster Cluster \
          --service Front \
          --force-new-deployment \
          --region us-east-1

          
    - name: Update ECS Server Service
      run: |
        aws ecs update-service \
          --cluster Cluster \
          --service Node \
          --force-new-deployment \
          --region us-east-1
