name: CI/CD EKS Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    -  name: Checkout Code
       uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Build and Tag Images
      run: |
        docker compose build 
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Tag image
      run: |
        docker tag react:latest mihirv21/python1app:client
        docker tag node:latest mihirv21/python1app:server
        
    -  name: Push Images
       run: |
         docker push mihirv21/python1app:client 
         docker push mihirv21/python1app:server
         
    - name: Update Kube Config
      run: |
        aws eks update-kubeconfig --name Kluster --region us-east-1
    
    - name: Deploy Secrets
      run: |
        kubectl apply -f react-secret.yaml
        kubectl apply -f node-secret.yaml
    

    - name: Deployment and Services
      run: | 
        kubectl apply -f node-deployment.yaml
        kubectl apply -f react-deployment.yaml
    
   
